# Generated by Django 6.0.4 on 2026-05-21 09:47

import django.core.files.storage
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import django_email_learning.models.enums.deactivation_reason
import django_email_learning.models.enums.delivery_status
import django_email_learning.models.enums.enrollment_status
import django_email_learning.models.imap_connections
import django_email_learning.services.utils
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# django_email_learning.migrations.0015_jobexecution_running_uniqueness


def deduplicate_running_jobexecutions(apps, schema_editor):  # type: ignore[no-untyped-def]
    JobExecution = apps.get_model("django_email_learning", "JobExecution")

    running_rows = JobExecution.objects.filter(status="running").order_by(
        "job_name", "-started_at", "-id"
    )

    latest_ids_by_job = {}
    duplicate_ids = []

    for row in running_rows:
        if row.job_name not in latest_ids_by_job:
            latest_ids_by_job[row.job_name] = row.id
            continue
        duplicate_ids.append(row.id)

    if duplicate_ids:
        now = django.utils.timezone.now()
        JobExecution.objects.filter(id__in=duplicate_ids).update(
            status="completed",
            finished_at=now,
        )


class Migration(migrations.Migration):
    replaces = [
        ("django_email_learning", "0001_initial"),
        ("django_email_learning", "0002_course_language"),
        ("django_email_learning", "0003_inboxfolder"),
        ("django_email_learning", "0004_alter_inboxfolder_imap_connection"),
        ("django_email_learning", "0005_course_target_audience_externalreference"),
        (
            "django_email_learning",
            "0006_organization_linkedin_page_organization_website_and_more",
        ),
        ("django_email_learning", "0007_course_is_public"),
        ("django_email_learning", "0008_organization_is_public"),
        ("django_email_learning", "0009_quiz_limited_attempts"),
        ("django_email_learning", "0010_quiz_is_blocking"),
        ("django_email_learning", "0011_alter_quiz_deadline_days"),
        ("django_email_learning", "0012_contentdelivery_remind_at_and_more"),
        ("django_email_learning", "0013_contentdelivery_reminder_state"),
        ("django_email_learning", "0014_learner_photo_alter_jobexecution_job_name"),
        ("django_email_learning", "0015_jobexecution_running_uniqueness"),
        ("django_email_learning", "0016_alter_jobexecution_job_name_and_more"),
        ("django_email_learning", "0017_alter_organizationuser_role"),
        ("django_email_learning", "0018_assignment_alter_coursecontent_type_and_more"),
        (
            "django_email_learning",
            "0019_alter_assignment_requires_file_submission_and_more",
        ),
        ("django_email_learning", "0020_assignment_reminder_interval_days"),
        ("django_email_learning", "0021_courseinstructor"),
        (
            "django_email_learning",
            "0022_organizationuser_display_name_organizationuser_photo",
        ),
        ("django_email_learning", "0023_assignmentsubmission_assignmentfeedback"),
        ("django_email_learning", "0024_alter_assignmentsubmission_delivery"),
        ("django_email_learning", "0025_alter_assignmentsubmission_status"),
        ("django_email_learning", "0026_alter_assignmentsubmission_delivery"),
        ("django_email_learning", "0027_alter_assignmentfeedback_submission"),
        ("django_email_learning", "0028_rename_comments_assignmentfeedback_comment"),
        ("django_email_learning", "0029_alter_assignmentsubmission_file_submission"),
        (
            "django_email_learning",
            "0030_organization_created_at_organization_updated_at_and_more",
        ),
        (
            "django_email_learning",
            "0031_alter_organizationuser_unique_together_and_more",
        ),
        ("django_email_learning", "0032_alter_assignmentsubmission_file_submission"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A short label for the course, used in URLs or email interactive actions. You can not edit it later."
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImapConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salt", models.CharField(editable=False, max_length=32)),
                (
                    "server",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django_email_learning.models.imap_connections.is_domain_or_ip
                        ],
                    ),
                ),
                ("port", models.IntegerField(db_default=993)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        choices=[("DELIVER_CONTENTS", "deliver_contents")],
                        max_length=200,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "running"), ("COMPLETED", "completed")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization_logos/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("priority", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "required_score",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "selection_strategy",
                    models.CharField(
                        choices=[
                            ("all", "All Questions"),
                            ("random", "Random Questions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "deadline_days",
                    models.IntegerField(
                        help_text="Time limit to complete the quiz in days. Minimum is 1 day and maximum is 30 days.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salt", models.CharField(editable=False, max_length=32)),
                (
                    "key",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(50)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("lesson", "Lesson"), ("quiz", "Quiz")], max_length=50
                    ),
                ),
                (
                    "waiting_period",
                    models.IntegerField(
                        help_text="Waiting period in seconds after previous content is sent or submited."
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.lesson",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_value", models.CharField(blank=True, max_length=64, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "course_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.coursecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                django_email_learning.models.enums.delivery_status.DeliveryStatus[
                                    "SCHEDULED"
                                ],
                                "Scheduled",
                            ),
                            (
                                django_email_learning.models.enums.delivery_status.DeliveryStatus[
                                    "PROCESSING"
                                ],
                                "Processing",
                            ),
                            (
                                django_email_learning.models.enums.delivery_status.DeliveryStatus[
                                    "DELIVERED"
                                ],
                                "Delivered",
                            ),
                            (
                                django_email_learning.models.enums.delivery_status.DeliveryStatus[
                                    "CANCELED"
                                ],
                                "Canceled",
                            ),
                            (
                                django_email_learning.models.enums.delivery_status.DeliveryStatus[
                                    "BLOCKED"
                                ],
                                "Blocked",
                            ),
                        ],
                        db_index=True,
                        default=django_email_learning.models.enums.delivery_status.DeliveryStatus[
                            "SCHEDULED"
                        ],
                        max_length=50,
                    ),
                ),
                ("failed_attempts", models.IntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedules",
                        to="django_email_learning.contentdelivery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("final_state_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                django_email_learning.models.enums.enrollment_status.EnrollmentStatus[
                                    "UNVERIFIED"
                                ],
                                "Unverified",
                            ),
                            (
                                django_email_learning.models.enums.enrollment_status.EnrollmentStatus[
                                    "ACTIVE"
                                ],
                                "Active",
                            ),
                            (
                                django_email_learning.models.enums.enrollment_status.EnrollmentStatus[
                                    "COMPLETED"
                                ],
                                "Completed",
                            ),
                            (
                                django_email_learning.models.enums.enrollment_status.EnrollmentStatus[
                                    "DEACTIVATED"
                                ],
                                "Deactivated",
                            ),
                        ],
                        default=django_email_learning.models.enums.enrollment_status.EnrollmentStatus[
                            "UNVERIFIED"
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "deactivation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                django_email_learning.models.enums.deactivation_reason.DeactivationReason[
                                    "CANCELED"
                                ],
                                "Canceled",
                            ),
                            (
                                django_email_learning.models.enums.deactivation_reason.DeactivationReason[
                                    "BLOCKED"
                                ],
                                "Blocked",
                            ),
                            (
                                django_email_learning.models.enums.deactivation_reason.DeactivationReason[
                                    "FAILED"
                                ],
                                "Failed",
                            ),
                            (
                                django_email_learning.models.enums.deactivation_reason.DeactivationReason[
                                    "INACTIVE"
                                ],
                                "Inactive",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activation_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.course",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.learner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentdelivery",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_deliveries",
                to="django_email_learning.enrollment",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("name_on_certificate", models.CharField(max_length=200)),
                ("random_suffix", models.IntegerField()),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="django_email_learning.enrollment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="imap_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_email_learning.imapconnection",
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.organization",
            ),
        ),
        migrations.AddField(
            model_name="imapconnection",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="django_email_learning.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="django_email_learning.quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("is_passed", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_submissions",
                        to="django_email_learning.contentdelivery",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="contentdelivery",
            unique_together={("enrollment", "course_content")},
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["unverified", "active", "completed"])
                ),
                fields=("learner", "course"),
                name="unique_active_enrollment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learner",
            unique_together={("organization", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("slug", "organization"), ("title", "organization")},
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("user", "organization")},
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("quiz__isnull", False)),
                fields=("course", "quiz"),
                name="unique_quiz_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lesson__isnull", False)),
                fields=("course", "lesson"),
                name="unique_lesson_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                fields=("course", "priority"), name="unique_priority_per_course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("af", "Afrikaans"),
                    ("ar", "Arabic"),
                    ("ar-dz", "Algerian Arabic"),
                    ("ast", "Asturian"),
                    ("az", "Azerbaijani"),
                    ("bg", "Bulgarian"),
                    ("be", "Belarusian"),
                    ("bn", "Bengali"),
                    ("br", "Breton"),
                    ("bs", "Bosnian"),
                    ("ca", "Catalan"),
                    ("ckb", "Central Kurdish (Sorani)"),
                    ("cs", "Czech"),
                    ("cy", "Welsh"),
                    ("da", "Danish"),
                    ("de", "German"),
                    ("dsb", "Lower Sorbian"),
                    ("el", "Greek"),
                    ("en", "English"),
                    ("en-au", "Australian English"),
                    ("en-gb", "British English"),
                    ("eo", "Esperanto"),
                    ("es", "Spanish"),
                    ("es-ar", "Argentinian Spanish"),
                    ("es-co", "Colombian Spanish"),
                    ("es-mx", "Mexican Spanish"),
                    ("es-ni", "Nicaraguan Spanish"),
                    ("es-ve", "Venezuelan Spanish"),
                    ("et", "Estonian"),
                    ("eu", "Basque"),
                    ("fa", "Persian"),
                    ("fi", "Finnish"),
                    ("fr", "French"),
                    ("fy", "Frisian"),
                    ("ga", "Irish"),
                    ("gd", "Scottish Gaelic"),
                    ("gl", "Galician"),
                    ("he", "Hebrew"),
                    ("hi", "Hindi"),
                    ("hr", "Croatian"),
                    ("hsb", "Upper Sorbian"),
                    ("ht", "Haitian Creole"),
                    ("hu", "Hungarian"),
                    ("hy", "Armenian"),
                    ("ia", "Interlingua"),
                    ("id", "Indonesian"),
                    ("ig", "Igbo"),
                    ("io", "Ido"),
                    ("is", "Icelandic"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("ka", "Georgian"),
                    ("kab", "Kabyle"),
                    ("kk", "Kazakh"),
                    ("km", "Khmer"),
                    ("kn", "Kannada"),
                    ("ko", "Korean"),
                    ("ky", "Kyrgyz"),
                    ("lb", "Luxembourgish"),
                    ("lt", "Lithuanian"),
                    ("lv", "Latvian"),
                    ("mk", "Macedonian"),
                    ("ml", "Malayalam"),
                    ("mn", "Mongolian"),
                    ("mr", "Marathi"),
                    ("ms", "Malay"),
                    ("my", "Burmese"),
                    ("nb", "Norwegian Bokmål"),
                    ("ne", "Nepali"),
                    ("nl", "Dutch"),
                    ("nn", "Norwegian Nynorsk"),
                    ("os", "Ossetic"),
                    ("pa", "Punjabi"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("pt-br", "Brazilian Portuguese"),
                    ("ro", "Romanian"),
                    ("ru", "Russian"),
                    ("sk", "Slovak"),
                    ("sl", "Slovenian"),
                    ("sq", "Albanian"),
                    ("sr", "Serbian"),
                    ("sr-latn", "Serbian Latin"),
                    ("sv", "Swedish"),
                    ("sw", "Swahili"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("tg", "Tajik"),
                    ("th", "Thai"),
                    ("tk", "Turkmen"),
                    ("tr", "Turkish"),
                    ("tt", "Tatar"),
                    ("udm", "Udmurt"),
                    ("ug", "Uyghur"),
                    ("uk", "Ukrainian"),
                    ("ur", "Urdu"),
                    ("uz", "Uzbek"),
                    ("vi", "Vietnamese"),
                    ("zh-hans", "Simplified Chinese"),
                    ("zh-hant", "Traditional Chinese"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="InboxFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_name", models.CharField(max_length=200)),
                (
                    "imap_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="django_email_learning.imapconnection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="target_audience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="django_email_learning.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="linkedin_page",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="youtube_channel",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="limited_attempts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_blocking",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="deadline_days",
            field=models.IntegerField(
                help_text="Time limit to complete the quiz in days. 0 indicates no deadline.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="contentdelivery",
            name="remind_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text="For quizzes without a deadline (deadline_days = 0), send reminder emails every N days.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="contentdelivery",
            name="reminder_state",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="not_applicable",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="learner",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="learner_photos/"),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("CHECK_IMAP", "check_imap"),
                    ("DELIVER_CONTENTS", "deliver_contents"),
                    ("SEND_REMINDERS", "send_reminders"),
                    ("DEACTIVATE_ENROLLMENTS", "deactivate_enrollments"),
                ],
                max_length=200,
            ),
        ),
        migrations.RunPython(
            code=deduplicate_running_jobexecutions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="jobexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("job_name",),
                name="unique_running_jobexecution_per_job",
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("check_imap", "CHECK_IMAP"),
                    ("deliver_contents", "DELIVER_CONTENTS"),
                    ("send_reminders", "SEND_REMINDERS"),
                    ("deactivate_enrollments", "DEACTIVATE_ENROLLMENTS"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[("running", "RUNNING"), ("completed", "COMPLETED")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("instructor", "Instructor"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the learner is required to submit the assignment to proceed to the next content.",
                    ),
                ),
                (
                    "deadline_days",
                    models.IntegerField(
                        help_text="Time limit to complete the assignment in days. 0 indicates no deadline.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "requires_text_submission",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the assignment requires text submission.",
                    ),
                ),
                (
                    "requires_file_submission",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the assignment requires file submission.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment__isnull", False)),
                fields=("course", "assignment"),
                name="unique_assignment_per_course",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="requires_file_submission",
            field=models.BooleanField(
                help_text="Whether the assignment requires file submission."
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="requires_text_submission",
            field=models.BooleanField(
                help_text="Whether the assignment requires text submission."
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text="For assignments without a deadline (deadline_days = 0), send reminder emails every N days.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="django_email_learning.course",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.organizationuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "org_user")},
            },
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="org_user_photos/"
            ),
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_submission", models.TextField(blank=True, null=True)),
                (
                    "file_submission",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/private_files/"
                        ),
                        upload_to="assignment_submissions/",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("requesting_changes", "Requesting Changes"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=50,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submission",
                        to="django_email_learning.contentdelivery",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_assignments",
                        to="django_email_learning.organizationuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("provided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_feedbacks",
                        to="django_email_learning.organizationuser",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="django_email_learning.assignmentsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="django_email_learning.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_user_organization"
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file_submission",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_email_learning.services.utils.get_private_file_storage,
                upload_to="assignment_submissions/",
            ),
        ),
    ]
