# Generated by Django 6.0.1 on 2026-01-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryschedule",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
