# Generated by Django 6.0 on 2026-01-07 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="next_send_timestamp",
        ),
    ]
