# Generated by Django 6.0.1 on 2026-01-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliveryschedule",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
