# Generated by Django 6.0.6 on 2026-07-10 05:52

from django.db import migrations, models

import django_email_learning.services.utils


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0002_newsletter_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django_email_learning.services.utils.get_private_file_storage,
                upload_to="learner_photos/",
            ),
        ),
    ]
