# Generated by Django 6.0.1 on 2026-01-17 05:08

import django_email_learning.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0002_learner_organization_alter_deliveryschedule_link",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryschedule",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="deliveryschedule",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        django_email_learning.models.DeliveryStatus["SCHEDULED"],
                        "Scheduled",
                    ),
                    (
                        django_email_learning.models.DeliveryStatus["PROCESSING"],
                        "Processing",
                    ),
                    (
                        django_email_learning.models.DeliveryStatus["DELIVERED"],
                        "Delivered",
                    ),
                    (
                        django_email_learning.models.DeliveryStatus["CANCELED"],
                        "Canceled",
                    ),
                    (django_email_learning.models.DeliveryStatus["BLOCKED"], "Blocked"),
                ],
                db_index=True,
                default=django_email_learning.models.DeliveryStatus["SCHEDULED"],
                max_length=50,
            ),
        ),
    ]
