# Generated by Django 6.0 on 2026-01-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0002_remove_enrollment_next_send_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentdelivery",
            name="delivery_schedules",
        ),
        migrations.AddField(
            model_name="deliveryschedule",
            name="delivery",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_schedules",
                to="django_email_learning.contentdelivery",
            ),
            preserve_default=False,
        ),
    ]
