# Generated by Django 5.2.8 on 2025-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0002_blockedemail_alter_imapconnection_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="waiting_period",
            field=models.IntegerField(
                default=5,
                help_text="Waiting period in seconds after previous content is sent or submited.",
            ),
            preserve_default=False,
        ),
    ]
