# Generated by Django 6.0.6 on 2026-07-09 11:40

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def mark_existing_certificates_as_already_sent(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Certificates issued before this migration predate PDF-email delivery.
    Mark them as already handled so the new background job doesn't
    retroactively email a PDF for every certificate ever issued.
    """
    Certificate = apps.get_model("django_email_learning", "Certificate")
    Certificate.objects.update(pdf_email_status="sent")


def noop_reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0002_newsletter_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_email_retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_email_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("processing", "Processing"), ("sent", "Sent"), ("failed", "Failed")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("check_imap", "CHECK_IMAP"),
                    ("deliver_contents", "DELIVER_CONTENTS"),
                    ("send_reminders", "SEND_REMINDERS"),
                    ("deactivate_enrollments", "DEACTIVATE_ENROLLMENTS"),
                    ("send_newsletters", "SEND_NEWSLETTERS"),
                    ("send_certificate_pdfs", "SEND_CERTIFICATE_PDFS"),
                ],
                max_length=200,
            ),
        ),
        migrations.RunPython(
            mark_existing_certificates_as_already_sent,
            reverse_code=noop_reverse,
        ),
    ]
