# Generated by Django 6.0.3 on 2026-04-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0002_course_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboxFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_name", models.CharField(max_length=200)),
                (
                    "imap_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_email_learning.imapconnection",
                    ),
                ),
            ],
        ),
    ]
