# Generated by Django 6.0.6 on 2026-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0003_learner_photo_private_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendout",
            name="denied_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sendout",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("sent", "Sent"), ("blocked", "Blocked")],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
