# Generated by Django 6.0.6 on 2026-06-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0003_sendout_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="newsletter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="django_email_learning.newsletter",
            ),
        ),
    ]
