# Generated by Django 6.0.3 on 2026-04-02 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0003_inboxfolder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxfolder",
            name="imap_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="django_email_learning.imapconnection",
            ),
        ),
    ]
