# Generated by Django 6.0 on 2026-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0003_remove_contentdelivery_delivery_schedules_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="is_published",
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
