# Generated by Django 5.2.8 on 2025-11-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0004_learner_enrollment_sentitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learner",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
