# Generated by Django 6.0 on 2026-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0004_remove_lesson_is_published_remove_quiz_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
