# Generated by Django 6.0.6 on 2026-06-26 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0004_course_newsletter_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendout",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="sendout",
            name="retry_count",
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("check_imap", "CHECK_IMAP"),
                    ("deliver_contents", "DELIVER_CONTENTS"),
                    ("send_reminders", "SEND_REMINDERS"),
                    ("deactivate_enrollments", "DEACTIVATE_ENROLLMENTS"),
                    ("send_newsletters", "SEND_NEWSLETTERS"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sendout",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("sent", "Sent")],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SendoutDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sendout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="django_email_learning.sendout",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sendout_deliveries",
                        to="django_email_learning.newslettersubscriber",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sendout", "subscriber"),
                        name="unique_sendout_delivery_per_subscriber",
                    )
                ],
            },
        ),
    ]
