# Generated by Django 6.0.6 on 2026-07-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0004_sendout_blocked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobexecution",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[("running", "RUNNING"), ("completed", "COMPLETED"), ("stale", "STALE"), ("failed", "FAILED")],
                max_length=50,
            ),
        ),
    ]
