# Generated by Django 6.0.3 on 2026-04-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0004_alter_inboxfolder_imap_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="target_audience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="django_email_learning.course",
                    ),
                ),
            ],
        ),
    ]
