# Generated by Django 5.2.8 on 2025-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0005_alter_learner_email"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["unverified", "active", "completed"])
                ),
                fields=("learner", "course"),
                name="unique_active_enrollment",
            ),
        ),
    ]
