# Generated by Django 6.0.6 on 2026-07-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0005_jobexecution_failed_status_and_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("website", "Website"), ("youtube", "YouTube"), ("linkedin", "LinkedIn")],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="django_email_learning.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["platform"],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "platform"), name="unique_organization_platform")
                ],
            },
        ),
    ]
