# Generated by Django 6.0.3 on 2026-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0005_course_target_audience_externalreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="linkedin_page",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="youtube_channel",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
