# Generated by Django 6.0.3 on 2026-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0006_organization_linkedin_page_organization_website_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
