# Generated by Django 5.2.8 on 2025-11-28 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0006_enrollment_unique_active_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentitem",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="sentitem",
            name="recorded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the item was recorded as sent. The actual send time may differ slightly depending on the email backend.",
            ),
            preserve_default=False,
        ),
    ]
