# Generated by Django 6.0.4 on 2026-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0007_course_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
