# Generated by Django 5.2.8 on 2025-11-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0007_remove_sentitem_sent_at_sentitem_recorded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(db_index=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="sentitem",
            unique_together={("enrollment", "course_content")},
        ),
        migrations.AddField(
            model_name="sentitem",
            name="times_sent",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sentitem",
            name="send_events",
            field=models.ManyToManyField(to="django_email_learning.eventtimestamp"),
        ),
        migrations.RemoveField(
            model_name="sentitem",
            name="recorded_at",
        ),
    ]
