# Generated by Django 6.0.6 on 2026-07-16 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0007_backfill_social_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="linkedin_page",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="website",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="youtube_channel",
        ),
    ]
