# Generated by Django 6.0.6 on 2026-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0008_remove_organization_legacy_social_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("x", "X (Twitter)"),
                    ("whatsapp", "WhatsApp Channel"),
                    ("telegram", "Telegram Channel"),
                    ("substack", "Substack"),
                ],
                max_length=20,
            ),
        ),
    ]
