# Generated by Django 6.0.4 on 2026-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0008_organization_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="limited_attempts",
            field=models.BooleanField(default=True),
        ),
    ]
