# Generated by Django 6.0.6 on 2026-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0009_add_more_social_link_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="embed_token",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
