# Generated by Django 6.0.4 on 2026-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0009_quiz_limited_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_blocking",
            field=models.BooleanField(default=True),
        ),
    ]
