# Generated by Django 6.0.4 on 2026-04-23 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0010_quiz_is_blocking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="deadline_days",
            field=models.IntegerField(
                help_text="Time limit to complete the quiz in days. 0 indicates no deadline.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
