# Generated by Django 6.0.6 on 2026-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0011_newsletter_subscriber_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentdelivery",
            name="opened_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryschedule",
            name="delivered_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="final_state_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
