# Generated by Django 6.0.4 on 2026-04-24 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0011_alter_quiz_deadline_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdelivery",
            name="remind_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text="For quizzes without a deadline (deadline_days = 0), send reminder emails every N days.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("CHECK_IMAP", "check_imap"),
                    ("DELIVER_CONTENTS", "deliver_contents"),
                    ("SEND_REMINDERS", "send_reminders"),
                ],
                max_length=200,
            ),
        ),
    ]
