# Generated by Django 6.0.4 on 2026-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0012_contentdelivery_remind_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdelivery",
            name="reminder_state",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not Applicable"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="not_applicable",
                max_length=50,
            ),
        ),
    ]
