# Generated by Django 6.0.6 on 2026-07-29 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0012_add_analytics_query_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="brand_color",
            field=models.CharField(
                default="#4A5EC0",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #4A5EC0.", regex="^#[0-9A-Fa-f]{6}$"
                    )
                ],
            ),
        ),
    ]
