# Generated by Django 6.0.6 on 2026-07-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0013_organization_brand_color"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobexecution",
            index=models.Index(fields=["job_name", "-started_at"], name="jobexecution_name_started_idx"),
        ),
    ]
