# Generated by Django 6.0.4 on 2026-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0013_contentdelivery_reminder_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="learner_photos/"),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("CHECK_IMAP", "check_imap"),
                    ("DELIVER_CONTENTS", "deliver_contents"),
                    ("SEND_REMINDERS", "send_reminders"),
                    ("DEACTIVATE_ENROLLMENTS", "deactivate_enrollments"),
                ],
                max_length=200,
            ),
        ),
    ]
