# Generated by Django 6.0.4 on 2026-04-28

from django.db import migrations, models
from django.utils import timezone


def deduplicate_running_jobexecutions(apps, schema_editor):  # type: ignore[no-untyped-def]
    JobExecution = apps.get_model("django_email_learning", "JobExecution")

    running_rows = JobExecution.objects.filter(status="running").order_by(
        "job_name", "-started_at", "-id"
    )

    latest_ids_by_job = {}
    duplicate_ids = []

    for row in running_rows:
        if row.job_name not in latest_ids_by_job:
            latest_ids_by_job[row.job_name] = row.id
            continue
        duplicate_ids.append(row.id)

    if duplicate_ids:
        now = timezone.now()
        JobExecution.objects.filter(id__in=duplicate_ids).update(
            status="completed",
            finished_at=now,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0014_learner_photo_alter_jobexecution_job_name"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_running_jobexecutions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="jobexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="running"),
                fields=("job_name",),
                name="unique_running_jobexecution_per_job",
            ),
        ),
    ]
