# Generated by Django 6.0.3 on 2026-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0015_jobexecution_running_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobexecution",
            name="job_name",
            field=models.CharField(
                choices=[
                    ("check_imap", "CHECK_IMAP"),
                    ("deliver_contents", "DELIVER_CONTENTS"),
                    ("send_reminders", "SEND_REMINDERS"),
                    ("deactivate_enrollments", "DEACTIVATE_ENROLLMENTS"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[("running", "RUNNING"), ("completed", "COMPLETED")],
                max_length=50,
            ),
        ),
    ]
