# Generated by Django 6.0.6 on 2026-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0015_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
