# Generated by Django 6.0.4 on 2026-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0016_alter_jobexecution_job_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("instructor", "Instructor"),
                    ("viewer", "Viewer"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
