# Generated by Django 6.0.4 on 2026-04-30 05:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0017_alter_organizationuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the learner is required to submit the assignment to proceed to the next content.",
                    ),
                ),
                (
                    "deadline_days",
                    models.IntegerField(
                        help_text="Time limit to complete the assignment in days. 0 indicates no deadline.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "requires_text_submission",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the assignment requires text submission.",
                    ),
                ),
                (
                    "requires_file_submission",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the assignment requires file submission.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assignment__isnull", False)),
                fields=("course", "assignment"),
                name="unique_assignment_per_course",
            ),
        ),
    ]
