# Generated by Django 6.0.4 on 2026-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0018_assignment_alter_coursecontent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="requires_file_submission",
            field=models.BooleanField(
                help_text="Whether the assignment requires file submission."
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="requires_text_submission",
            field=models.BooleanField(
                help_text="Whether the assignment requires text submission."
            ),
        ),
    ]
