# Generated by Django 6.0.4 on 2026-04-30 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0019_alter_assignment_requires_file_submission_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text="For assignments without a deadline (deadline_days = 0), send reminder emails every N days.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
