# Generated by Django 6.0.7 on 2026-08-25 08:37

from django.db import migrations, models

import django_email_learning.models.enums.deactivation_reason


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0020_deliveryschedule_claimed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["CANCELED"], "Canceled"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["BLOCKED"], "Blocked"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["FAILED"], "Failed"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["INACTIVE"], "Inactive"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["REVOKED"], "Revoked"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
