# Generated by Django 6.0.4 on 2026-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0021_courseinstructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="org_user_photos/"
            ),
        ),
    ]
