# Generated by Django 6.0.7 on 2026-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0021_alter_enrollment_deactivation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="from_email_type",
            field=models.CharField(
                choices=[("platform_default", "Platform Default"), ("organization", "Organization")],
                default="platform_default",
                help_text="Which address course content emails are sent from.",
                max_length=32,
            ),
        ),
    ]
