# Generated by Django 6.0.7 on 2026-08-31 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0022_course_from_email_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdelivery",
            name="reminder_count",
            field=models.IntegerField(
                default=0, help_text="How many reminder emails have been sent for this delivery."
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text=(
                    "For assignments without a deadline (deadline_days = 0), send a reminder email every N days "
                    "until the learner submits, up to 3 reminders. 0 or empty means no reminders."
                ),
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="reminder_interval_days",
            field=models.IntegerField(
                blank=True,
                help_text=(
                    "For quizzes without a deadline (deadline_days = 0), send a reminder email every N days "
                    "until the learner completes the quiz, up to 3 reminders. 0 or empty means no reminders."
                ),
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
