# Generated by Django 6.1 on 2026-08-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0023_contentdelivery_reminder_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="show_organization_footer",
            field=models.BooleanField(
                default=False,
                help_text="Show the organization name and social links in the footer of this course's emails.",
            ),
        ),
    ]
