# Generated by Django 6.0.4 on 2026-05-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0023_assignmentsubmission_assignmentfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="delivery",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to="django_email_learning.contentdelivery",
            ),
        ),
    ]
