# Generated by Django 6.1 on 2026-09-04 04:51

from django.db import migrations, models

from django_email_learning.models.validators import (
    MAX_ORGANIZATION_NAME_LENGTH,
    validate_organization_name,
    validate_safe_name,
)


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0024_course_show_organization_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, validators=[validate_safe_name]),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                max_length=MAX_ORGANIZATION_NAME_LENGTH,
                validators=[validate_organization_name],
            ),
        ),
    ]
