# Generated by Django 6.0.4 on 2026-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0024_alter_assignmentsubmission_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("requesting_changes", "Requesting Changes"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_review",
                max_length=50,
            ),
        ),
    ]
