# Generated by Django 6.1 on 2026-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0025_alter_course_title_alter_organization_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmission",
            name="asked_question_ids",
            field=models.JSONField(
                blank=True, help_text="IDs of the questions this learner was shown, resolved at grade time.", null=True
            ),
        ),
        migrations.AddField(
            model_name="quizsubmission",
            name="selected_answer_ids",
            field=models.JSONField(
                blank=True,
                help_text="Question ID (as a string, per JSON) to the answer IDs the learner selected.",
                null=True,
            ),
        ),
    ]
