# Generated by Django 6.0.4 on 2026-05-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0026_alter_assignmentsubmission_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentfeedback",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="django_email_learning.assignmentsubmission",
            ),
        ),
    ]
