# Generated by Django 6.1 on 2026-09-12 09:19

import django.db.models.deletion
from django.db import migrations, models

import django_email_learning.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0026_quizsubmission_asked_question_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        max_length=200, validators=[django_email_learning.models.validators.validate_safe_name]
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="coursecontent",
            name="unique_priority_per_course",
        ),
        migrations.AddField(
            model_name="contenttrack",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_tracks",
                to="django_email_learning.course",
            ),
        ),
        migrations.AddField(
            model_name="contenttrack",
            name="merge_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a learner continues after the last content on this track. Empty ends the course.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merging_tracks",
                to="django_email_learning.coursecontent",
            ),
        ),
        migrations.AddField(
            model_name="contenttrack",
            name="parent_track",
            field=models.ForeignKey(
                blank=True,
                help_text="The track this one branches off. Empty means it branches off the main spine.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_tracks",
                to="django_email_learning.contenttrack",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="track",
            field=models.ForeignKey(
                blank=True,
                help_text="The branch this content belongs to. Empty means the course's main spine.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contents",
                to="django_email_learning.contenttrack",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("track__isnull", True)),
                fields=("course", "priority"),
                name="unique_priority_per_course_spine",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("track__isnull", False)),
                fields=("course", "track", "priority"),
                name="unique_priority_per_track",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contenttrack",
            unique_together={("course", "name")},
        ),
    ]
