# Generated by Django 6.0.4 on 2026-05-06 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0027_alter_assignmentfeedback_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentfeedback",
            old_name="comments",
            new_name="comment",
        ),
    ]
