# Generated by Django 6.1 on 2026-09-12 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0027_contenttrack_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(help_text="Rules are evaluated low to high and the first match wins.")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("score_gte", "Score Gte"),
                            ("score_lt", "Score Lt"),
                            ("default", "Default"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="The score this rule compares against. Required for a score condition.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="django_email_learning.coursecontent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="django_email_learning.contenttrack",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("source", "order"), name="unique_transition_order_per_source"),
                    models.UniqueConstraint(
                        condition=models.Q(("condition", "default")),
                        fields=("source",),
                        name="single_default_transition_per_source",
                    ),
                ],
            },
        ),
    ]
