# Generated by Django 6.0.4 on 2026-05-07 05:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0028_rename_comments_assignmentfeedback_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file_submission",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/private_files/"
                ),
                upload_to="assignment_submissions/",
            ),
        ),
    ]
