# Generated by Django 6.1 on 2026-09-13 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0028_contenttransition"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DecisionPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("prompt", models.TextField()),
                (
                    "deadline_days",
                    models.IntegerField(
                        default=0,
                        help_text="Time limit to answer in days. 0 indicates no deadline.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reminder_interval_days",
                    models.IntegerField(
                        blank=True,
                        help_text=(
                            "For decisions without a deadline (deadline_days = 0), send a reminder email every N days "
                            "until the learner answers, up to 3 reminders. 0 or empty means no reminders."
                        ),
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contenttransition",
            name="condition",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("score_gte", "Score Gte"),
                    ("score_lt", "Score Lt"),
                    ("default", "Default"),
                    ("option_selected", "Option Selected"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("decision", "Decision"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contenttransition",
            name="option",
            field=models.ForeignKey(
                blank=True,
                help_text="The option this rule matches. Required for an option condition.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="django_email_learning.decisionoption",
            ),
        ),
        migrations.AddField(
            model_name="decisionoption",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="django_email_learning.decisionpoint",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_email_learning.decisionpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("decision__isnull", False)),
                fields=("course", "decision"),
                name="unique_decision_per_course",
            ),
        ),
        migrations.AddField(
            model_name="decisionresponse",
            name="delivery",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_response",
                to="django_email_learning.contentdelivery",
            ),
        ),
        migrations.AddField(
            model_name="decisionresponse",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="django_email_learning.decisionoption",
            ),
        ),
    ]
