# Generated by Django 6.1 on 2026-09-21 09:48

import django.db.models.deletion
from django.db import migrations, models

import django_email_learning.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0029_decisionpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The course's certificate fields as they stood when this certificate was issued.",
            ),
        ),
        migrations.CreateModel(
            name="CertificateField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        max_length=50, validators=[django_email_learning.models.validators.validate_safe_name]
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=100, validators=[django_email_learning.models.validators.validate_safe_name]
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_fields",
                        to="django_email_learning.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
