# Generated by Django 6.0.4 on 2026-05-14 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0030_organization_created_at_organization_updated_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="organizationuser",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_user_organization"
            ),
        ),
    ]
