# Generated by Django 6.1.1 on 2026-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0030_certificate_custom_fields_certificatefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="favicon",
            field=models.ImageField(blank=True, editable=False, null=True, upload_to="organization_logos/"),
        ),
    ]
