# Generated by Django 6.0.4 on 2026-05-14 08:08

import django_email_learning.services.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0031_alter_organizationuser_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file_submission",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_email_learning.services.utils.get_private_file_storage,
                upload_to="assignment_submissions/",
            ),
        ),
    ]
