# Generated by Django 6.0.5 on 2026-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_email_learning",
            "0001_initial_squashed_0032_alter_assignmentsubmission_file_submission",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "RUNNING"),
                    ("completed", "COMPLETED"),
                    ("stale", "STALE"),
                ],
                max_length=50,
            ),
        ),
    ]
