# Generated by Django 6.0.6 on 2026-06-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0034_contentdelivery_opened_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="django_email_learning.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="learner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="django_email_learning.learner",
            ),
        ),
    ]
