# Generated by Django 6.0.6 on 2026-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0035_enrollment_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="send_certificate",
            field=models.BooleanField(default=True),
        ),
    ]
