# Generated by Django 6.1.1 on 2026-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0035_repair_organization_slug_underscores"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendout",
            name="skipped_reason",
            field=models.CharField(
                blank=True, choices=[("no_confirmed_subscribers", "No confirmed subscribers")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sendout",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("sent", "Sent"), ("blocked", "Blocked"), ("skipped", "Skipped")],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
