# Generated by Django 6.1.1 on 2026-10-09 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_email_learning.models.enums.deactivation_reason


class Migration(migrations.Migration):
    dependencies = [
        ("django_email_learning", "0036_sendout_skipped_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="What the learner waits for, e.g. 'Payment'. Shown on the public course page.",
                        max_length=500,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Names this gate in the unlock API. Unique within a course.", max_length=100
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Emailed to the learner when they reach the gate. Empty sends nothing.",
                    ),
                ),
                (
                    "timeout_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days to wait for an unlock before `timeout_action` applies. 0 waits indefinitely.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "timeout_action",
                    models.CharField(
                        choices=[("deactivate", "Deactivate the enrollment"), ("continue", "Continue past the gate")],
                        default="deactivate",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateUnlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("api", "API"), ("admin", "Admin"), ("timeout", "Timeout")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("decision", "Decision"),
                    ("gate", "Gate"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["CANCELED"], "Canceled"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["BLOCKED"], "Blocked"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["FAILED"], "Failed"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["INACTIVE"], "Inactive"),
                    (django_email_learning.models.enums.deactivation_reason.DeactivationReason["REVOKED"], "Revoked"),
                    (
                        django_email_learning.models.enums.deactivation_reason.DeactivationReason["GATE_EXPIRED"],
                        "Gate expired",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="gate",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="django_email_learning.gate"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gate__isnull", False)), fields=("course", "gate"), name="unique_gate_per_course"
            ),
        ),
        migrations.AddField(
            model_name="gateunlock",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="The key the unlock call was made with, when source is api.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_email_learning.apikey",
            ),
        ),
        migrations.AddField(
            model_name="gateunlock",
            name="course_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gate_unlocks",
                to="django_email_learning.coursecontent",
            ),
        ),
        migrations.AddField(
            model_name="gateunlock",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gate_unlocks",
                to="django_email_learning.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="gateunlock",
            name="unlocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who unlocked it, when source is admin.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="gateunlock",
            constraint=models.UniqueConstraint(fields=("enrollment", "course_content"), name="unique_gate_unlock"),
        ),
    ]
