# Generated by Django 6.0.4 on 2026-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth_integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
