from django.urls import path
from django.views.defaults import page_not_found

from django_email_learning.platform.api.views import (
    ApiKeyView,
    CourseContentView,
    CourseView,
    EmbedSnippetView,
    EnrollmentsStatisticsView,
    EnrollmentsView,
    EnrollmentView,
    FileView,
    GetOrCreateUserByEmail,
    ImapConnectionView,
    JobsStatus,
    LearnersView,
    NewsletterEmbedSnippetView,
    NewsletterView,
    OauthGetGroupListView,
    OauthGroupEnrollment,
    OauthSessionView,
    OrganizationsView,
    OrganizationUsersView,
    ReorderCourseContentView,
    SendLessonToPlatformUser,
    SendoutView,
    SingleApiKeyView,
    SingleCourseContentView,
    SingleCourseView,
    SingleLearnerView,
    SingleNewsletterView,
    SingleOrganizationUserView,
    SingleOrganizationView,
    SingleSendoutView,
    SingleSubscriberView,
    SubmissionReview,
    SubmittedAssignmentDetailView,
    SubmittedAssignmentsView,
    SubscribersCsvExportView,
    SubscriberView,
    UpdateSessionView,
)

app_name = "django_email_learning"

urlpatterns = [
    path(
        "organizations/<int:organization_id>/courses/",
        CourseView.as_view(),
        name="courses_list",
    ),
    path(
        "organizations/<int:organization_id>/users/",
        OrganizationUsersView.as_view(),
        name="organization_users_list",
    ),
    path(
        "organizations/<int:organization_id>/users/<int:user_id>/",
        SingleOrganizationUserView.as_view(),
        name="organization_users_detail",
    ),
    path(
        "organizations/<int:organization_id>/imap-connections/",
        ImapConnectionView.as_view(),
        name="imap_connections_list",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/",
        NewsletterView.as_view(),
        name="newsletters_list",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/",
        SingleNewsletterView.as_view(),
        name="newsletters_detail",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/sendouts/",
        SendoutView.as_view(),
        name="sendouts_list",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/sendouts/<int:sendout_id>/",
        SingleSendoutView.as_view(),
        name="sendouts_detail",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/embed_snippet/",
        NewsletterEmbedSnippetView.as_view(),
        name="newsletter_embed_snippet",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/subscribers/",
        SubscriberView.as_view(),
        name="newsletter_subscribers_list",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/subscribers/<int:subscriber_id>/",
        SingleSubscriberView.as_view(),
        name="newsletter_subscriber_detail",
    ),
    path(
        "organizations/<int:organization_id>/newsletters/<int:newsletter_id>/subscribers/export.csv",
        SubscribersCsvExportView.as_view(),
        name="newsletter_subscribers_csv",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/",
        SingleCourseView.as_view(),
        name="courses_detail",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/embed_snippet/",
        EmbedSnippetView.as_view(),
        name="course_embed_snippet",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/contents/",
        CourseContentView.as_view(),
        name="course_contents_list",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/contents/reorder/",
        ReorderCourseContentView.as_view(),
        name="course_contents_reorder",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/contents/<int:course_content_id>/",
        SingleCourseContentView.as_view(),
        name="course_contents_detail",
    ),
    path(
        "organizations/<int:organization_id>/learners/",
        LearnersView.as_view(),
        name="learners_list",
    ),
    path(
        "organizations/<int:organization_id>/learners/<int:learner_id>/",
        SingleLearnerView.as_view(),
        name="learners_detail",
    ),
    path(
        "organizations/<int:organization_id>/enrollments/<int:enrollment_id>/",
        EnrollmentView.as_view(),
        name="enrollments_detail",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/enrollments/",
        EnrollmentsView.as_view(),
        name="enrollments_list",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/enrollments/statistics/",
        EnrollmentsStatisticsView.as_view(),
        name="enrollments_statistics",
    ),
    path(
        "organizations/<int:organization_id>/send-lesson/",
        SendLessonToPlatformUser.as_view(),
        name="send_lesson",
    ),
    path(
        "organizations/<int:organization_id>/files/",
        FileView.as_view(),
        name="files_list",
    ),
    path("organizations/", OrganizationsView.as_view(), name="organizations_list"),
    path(
        "organizations/<int:organization_id>/",
        SingleOrganizationView.as_view(),
        name="organizations_detail",
    ),
    path(
        "organizations/<int:organization_id>/oauth-session/<str:session_id>/",
        OauthSessionView.as_view(),
        name="oauth_sessions_detail",
    ),
    path(
        "organizations/<int:organization_id>/oauth-session/<str:session_id>/get_groups",
        OauthGetGroupListView.as_view(),
        name="oauth_sessions_groups",
    ),
    path(
        "organizations/<int:organization_id>/oauth-session/<str:session_id>/enroll_users",
        OauthGroupEnrollment.as_view(),
        name="oauth_sessions_enroll",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/submitted_assignments/",
        SubmittedAssignmentsView.as_view(),
        name="submitted_assignments_list",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/submitted_assignments/<int:submission_id>",
        SubmittedAssignmentDetailView.as_view(),
        name="submitted_assignments_detail",
    ),
    path(
        "organizations/<int:organization_id>/courses/<int:course_id>/submitted_assignments/<int:submission_id>/review/",
        SubmissionReview.as_view(),
        name="submission_review",
    ),
    path("status/jobs/", JobsStatus.as_view(), name="jobs_status"),
    path("api_keys/", ApiKeyView.as_view(), name="api_keys_list"),
    path(
        "api_keys/<int:api_key_id>/",
        SingleApiKeyView.as_view(),
        name="api_keys_detail",
    ),
    path(
        "users/get-or-create-by-email/",
        GetOrCreateUserByEmail.as_view(),
        name="get_or_create_user_by_email",
    ),
    path("session", UpdateSessionView.as_view(), name="update_session"),
    path("", page_not_found, name="root"),
]
